name: Rainix CI
on: [push]

jobs:
  rainix:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        task: [rainix-rs-test, rainix-rs-artifacts]
        include:
          # We don't need to do rust static analysis on multiple platforms
          - os: ubuntu-latest
            task: rainix-rs-static
      fail-fast: false
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - uses: DeterminateSystems/nix-installer-action@v4
      - uses: DeterminateSystems/magic-nix-cache-action@v2

      - run: nix run .#rainix-rs-prelude

      - name: Run ${{ matrix.task }}
        run: nix run .#${{ matrix.task }}

      - name: Build JS Bindings
        run:  nix run .#build-js-bindings
      
      - name: Run JS Tests
        run:  nix run .#test-js-bindings

      - name: Test JS Doc Generation
        run:  nix run .#js-bindings-docs