name: Standard Test
on: [push, pull_request]
jobs:
  build-lint-test:
    name: Build, lint, test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Install nix
        uses: cachix/install-nix-action@v13
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Build
        run: nix run ./#build --extra-experimental-features nix-command --extra-experimental-features flakes

      - name: Lint
        run: nix run ./#lint --extra-experimental-features nix-command --extra-experimental-features flakes

      - name: Test
        run: nix run ./#local-test --extra-experimental-features nix-command --extra-experimental-features flakes

      - name: Test Docs Generation
        run: nix run ./#docgen --extra-experimental-features nix-command --extra-experimental-features flakes