name: Standard Test
on: [push, pull_request]
jobs:
  build-lint-test:
    name: Build, lint, test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Install nix
        uses: cachix/install-nix-action@v13
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Build
        run: nix-shell

      - name: Lint
        run: nix-shell --run lint

      - name: Test
        run: nix-shell --run local-test

      - name: Test Docs Generation
        run: nix-shell --run docgen