name: Test
on: [push]

jobs:
  release_bin:
    name: Release dotrain cli ${{ matrix.platform }}_${{ matrix.arch }} bin
    runs-on: ${{ matrix.runner }}
    strategy:
      fail-fast: false
      matrix:
        include:          
          - runner: ubuntu-22.04
            target: x86_64-unknown-linux-gnu
            platform: linux
            arch: x86_64
          - runner: macos-13
            target: x86_64-apple-darwin
            platform: darwin
            arch: x86_64
          - runner: macos-14
            target: aarch64-apple-darwin
            platform: darwin
            arch: arm64

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive
          ssh-key: ${{ secrets.PUBLISHER_SSH_KEY }}

      - uses: DeterminateSystems/nix-installer-action@v4
      - uses: DeterminateSystems/magic-nix-cache-action@v2

      - name: Git Config
        run: |
          git config --global user.email "${{ secrets.CI_GIT_EMAIL }}"
          git config --global user.name "${{ secrets.CI_GIT_USER }}"

      - name: Pull Release Commit
        run: git pull origin

      - run: ls -l

      - name: Build Bin
        run: nix develop -c cargo build -r --features cli --bin dotrain --target "${{ matrix.target }}"

      - run: ls -l
      - run: cd target && ls -l
      - run: cd target/${{ matrix.target }} && ls -l
      - run: nix develop -c cp ./target/release/dotrain ./dotrain_cli
